import JSZip from 'jszip'
import { engineTargets, getCategory, getPalette, getStyle } from '../data/catalog'
import type { EngineTarget, GameAsset } from '../types'

export function assetMetadata(asset: GameAsset, target: EngineTarget) {
  const engine = engineTargets.find((item) => item.id === target) ?? engineTargets[0]

  return {
    schema: 'spritecraft.asset.v1',
    name: asset.name,
    category: getCategory(asset.categoryId).label,
    source: asset.source,
    engine: engine.id,
    engineRoot: engine.root,
    size: asset.size,
    frameCount: asset.frameCount,
    style: getStyle(asset.styleId).label,
    palette: getPalette(asset.paletteId),
    seed: asset.seed,
    tags: asset.tags,
    usage: asset.usage,
    files: {
      preview: `${asset.name}.png`,
      spriteSheet: `${asset.name}.sheet.png`,
      metadata: `${asset.name}.metadata.json`,
    },
    createdAt: asset.createdAt,
  }
}

export function downloadText(filename: string, content: string, type = 'application/json') {
  downloadBlob(filename, new Blob([content], { type }))
}

export function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.append(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
}

export async function imageSourceToBlob(source: string) {
  const response = await fetch(source)
  return response.blob()
}

async function loadImage(source: string) {
  return new Promise<HTMLImageElement>((resolve, reject) => {
    const image = new Image()
    image.onload = () => resolve(image)
    image.onerror = () => reject(new Error('Failed to load frame image'))
    image.src = source
  })
}

export async function buildSpriteSheet(asset: GameAsset) {
  const frameImages = await Promise.all(asset.frames.map(loadImage))
  const [width, height] = asset.size.split('x').map(Number)
  const canvas = document.createElement('canvas')
  canvas.width = width * frameImages.length
  canvas.height = height
  const context = canvas.getContext('2d')

  if (!context) {
    throw new Error('Canvas is unavailable')
  }

  context.imageSmoothingEnabled = false
  frameImages.forEach((image, index) => {
    context.drawImage(image, index * width, 0, width, height)
  })

  return new Promise<Blob>((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (!blob) {
        reject(new Error('Failed to render sprite sheet'))
        return
      }
      resolve(blob)
    }, 'image/png')
  })
}

export async function exportEngineZip(asset: GameAsset, target: EngineTarget) {
  const engine = engineTargets.find((item) => item.id === target) ?? engineTargets[0]
  const root = engine.root.replace(/^res:\/\//, '').replace(/^public\//, '')
  const zip = new JSZip()
  const previewBlob = await imageSourceToBlob(asset.imageSrc)
  const sheetBlob = await buildSpriteSheet(asset)
  const metadata = JSON.stringify(assetMetadata(asset, target), null, 2)

  zip.file(`${root}/sprites/${asset.name}.png`, previewBlob)
  zip.file(`${root}/sprites/${asset.name}.sheet.png`, sheetBlob)
  zip.file(`${root}/metadata/${asset.name}.metadata.json`, metadata)
  zip.file(
    `${root}/README.md`,
    [
      `# ${asset.name}`,
      '',
      `Target engine: ${engine.label}`,
      `Generated by: SpriteCraft Studio`,
      `Usage: ${asset.usage}`,
      '',
      'Import the PNG files into your sprite folder and keep the metadata JSON beside the asset for pipeline automation.',
    ].join('\n'),
  )

  downloadBlob(`${asset.name}.${target}.zip`, await zip.generateAsync({ type: 'blob' }))
}
